realclean: traceclean
	rm -rf src_*

traceclean: clean
	rm -rf src_*/*.trace.xml

clean:
	rm -rf src_*/*.c
	rm -rf src_*/*.h
	rm -rf src_*/*.plu
	rm -rf src_*/*.df
	rm -rf src_*/*.lusic
	rm -rf *.mexa64
	rm -rf slprj/
