function cellInfo = bus_mess_test_struct(varargin) 
% BUS_MESS_TEST_STRUCT returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BusA', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'a', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a1', [2 3], 'int16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a2', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a3', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BusB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'b', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'b1', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'b2', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'b3', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BusDT', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'a', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'a1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BusUnif', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'f', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'f1', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BusUnif3', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'f3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'f', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'f1', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
