/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _CONV
#define _CONV

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */

/* Nodes declarations */
extern double int_to_real (int in1
                           );

extern int real_to_int (double in1
                        );


#endif

