/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _MATH
#define _MATH

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */

/* Nodes declarations */
extern double sqrt (double x
                    );

extern double sinh (double x
                    );

extern double sin (double x
                   );

extern double pow (double x, double n
                   );

extern double fabs (double x
                    );

extern double erf (double x
                   );

extern double ceil (double x
                    );

extern double cosh (double x
                    );

extern double cos (double x
                   );

extern double cbrt (double x
                    );

extern double atanh (double x
                     );

extern double atan2 (double x, double n
                     );

extern double atan (double x
                    );

extern double asinh (double x
                     );

extern double asin (double x
                    );

extern double acosh (double x
                     );

extern double acos (double x
                    );


#endif

